### PR TITLE
`joinLoc` for different filenames

### LINKED ISSUE #54: `Unimplemented: joinLoc` `Errormsg.Error while parsing` on `bench`
[bench/coreutils](https://github.com/goblint/bench/tree/master/coreutils) but also others now fail with an exception while parsing:

~~~
./goblint -v coreutils/cksum_comb.c --enable exp.solver.td3.term --enable exp.earlyglobs --enable ana.int.interval --disable ana.int.enums --disable ana.int.def_exc --disable ana.context.widen --sets exp.privatization none --disable exp.solver.td3.space_restore --sets dbg.timeout 6h --sets save_run out/coreutils/cksum_comb.c.enable-term
Custom include dirs:
  1. /home/voglerr/bench/includes (exists=true)
Preprocessing files.
Preprocessor cpp: is_bad=false
cpp --undef __BLOCKS__ '-I' '/home/voglerr/bench/includes' "/home/voglerr/bench/includes/stdlib.c" -o "/home/voglerr/bench/goblint_temp_68b1cf/stdlib.c"
cpp --undef __BLOCKS__ '-I' '/home/voglerr/bench/includes' "coreutils/cksum_comb.c" -o "/home/voglerr/bench/goblint_temp_68b1cf/cksum_comb.c"
Parsing files.
Frontc is parsing /home/voglerr/bench/goblint_temp_68b1cf/stdlib.c
Converting CABS->CIL
Frontc is parsing /home/voglerr/bench/goblint_temp_68b1cf/cksum_comb.c
Unimplemented: joinLoc parse-datetime.c:1765:3--1:-1 parse-datetime.y:325:38--1:-1
Caught Errormsg.Error while parsing
Fatal error: exception Errormsg.Error
Raised at Frontc.parse_to_cabs_inner in file "src/frontc/frontc.ml", line 210, characters 6-13
Called from Frontc.parse_to_cabs in file "src/frontc/frontc.ml", line 121, characters 13-38
Called from Frontc.parse_helper in file "src/frontc/frontc.ml", line 256, characters 13-32
Called from Frontc.parse in file "src/frontc/frontc.ml" (inlined), line 264, characters 32-55
Called from Cilfacade.parse in file "src/util/cilfacade.ml", line 48, characters 2-26
Called from Stdlib__list.rev_map.rmap_f in file "list.ml", line 103, characters 22-25
Called from Maingoblint.merge_preprocessed in file "src/maingoblint.ml", line 292, characters 18-62
Called from Maingoblint.main in file "src/maingoblint.ml", line 505, characters 15-56
Called from Stdlib.at_exit.new_exit in file "stdlib.ml", line 554, characters 59-63
Called from Stdlib.do_at_exit in file "stdlib.ml" (inlined), line 560, characters 20-61
Called from Std_exit in file "std_exit.ml", line 18, characters 8-20
Command exited with non-zero status 2
	Command being timed: "./goblint -v coreutils/cksum_comb.c --enable exp.solver.td3.term --enable exp.earlyglobs --enable ana.int.interval --disable ana.int.enums --disable ana.int.def_exc --disable ana.context.widen --sets exp.privatization none --disable exp.solver.td3.space_restore --sets dbg.timeout 6h --sets save_run out/coreutils/cksum_comb.c.enable-term"
	User time (seconds): 0.18
	System time (seconds): 0.04
	Percent of CPU this job got: 98%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.23
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 33896
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 7728
	Voluntary context switches: 20
	Involuntary context switches: 1
	Swaps: 0
	File system inputs: 0
	File system outputs: 3768
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 2
~~~

### PR DESCRIPTION
**Pull request by vogler**
Fix #54.

### CODE REVIEW

**Comment by vogler** [comment]
Just returning the left location does not work:

~~~
fd-reopen.c:34: Error: Cannot resolve variable tmp.
Error: There were errors during merging

Fatal error: exception Errormsg.Error
Raised at Errormsg.s in file "src/ocamlutil/errormsg.ml" (inlined), line 49, characters 17-28
Called from Cilfacade.getMergedAST in file "src/util/cilfacade.ml", line 153, characters 4-54
Called from Maingoblint.merge_preprocessed in file "src/maingoblint.ml", line 310, characters 12-37
Called from Maingoblint.main in file "src/maingoblint.ml", line 505, characters 15-56
Called from Stdlib.at_exit.new_exit in file "stdlib.ml", line 554, characters 59-63
Called from Stdlib.do_at_exit in file "stdlib.ml" (inlined), line 560, characters 20-61
Called from Std_exit in file "std_exit.ml", line 18, characters 8-20
~~~

**Comment by vogler** [comment]
Removing the `filename` equality checks gives the same result.

**Comment by sim642** [comment]
> Just returning the left location does not work:

This should work because returning `l1` is just as good as it was before #51, only having start locations.

The first error there is
```
/usr/include/bits/stdlib.h:46: Error: Invalid position for (prefix) function type attributes: __attribute__((__warn_unused_result__,
__artificial__)) 
```
which seems related to #52, where some support for some attribute placement was removed.

**Comment by sim642** [comment]
Actually, I'm not even sure if it's related to #52, because the code in question is this:
```c
#line 46
    return ((char __attribute__((__warn_unused_result__, __artificial__))  *)tmp___0);
```
Both of those attributes are for functions, but there's no function here at all, so it's actually not even valid to use these attributes in this type. How has this ever worked?

**EDIT:** GCC currently just warns about this:
```
/usr/include/bits/stdlib.h:46:5: warning: ‘warn_unused_result’ attribute only applies to function types [-Wattributes]
/usr/include/bits/stdlib.h:46:5: warning: ‘artificial’ attribute does not apply to types [-Wattributes]
```
I don't know that we've ever made CIL more strict about this though.

It looks like maybe the merging process has incorrectly put copied these attributes there when forcing a cast to the function return type:
```
__inline extern char __attribute__((__warn_unused_result__, __artificial__))  *( __attribute__((__always_inline__)) realpath)(char const   * __restrict  __name ,
                                                                                                                              char * __restrict  __resolved ) 
```
It's just that those attributes are for the function, not the type.

**Comment by sim642** [comment]
I opened a new PR #56 which allows `cksum_comb.c` at least to be parsed and analyzed, so I'll close this.

**Pull request closed without merging**
