### PR TITLE
Revert "Fix TCompLoop printing being stateful"

### PR DESCRIPTION
**Pull request by michael-schwarz**
This reverts commit eded39ed7af8aa4b1c3b024dc2a8c7f6fe07c488. (c.f. #134)

It causes non-termination of the printers (see https://github.com/goblint/analyzer/issues/1290)

### CODE REVIEW

**Comment by sim642** [comment]
Instead of just reverting, I think we should figure out why #134 should somehow cause non-termination because that's not clear at all. It's only removing things which weren't in the hashtable before and were just added.

By never removing them, the visited structs just accumulate and the extraneously accumulated structs somehow prune evaluation. But that pruned evaluation isn't then happening recursively from within the modified block, rather somewhere later in some sequential process. But that seems like something else odd is also going on.

**Comment by michael-schwarz** [comment]
> But that pruned evaluation isn't then happening recursively from within the modified block, rather somewhere later in some sequential process. But that seems like something else odd is also going on.

The sampling seems to point at the recursion happening entirely within `pOnlyType`.

**Comment by michael-schwarz** [comment]
One idea: Maybe something is delayed by these `doc` things that are everywhere and then only evaluated later?

**Comment by sim642** [comment]
> One idea: Maybe something is delayed by these `doc` things that are everywhere and then only evaluated later?

That can't be because the `Pretty.doc` is just an ADT of strings and nothing delayable.

**Comment by michael-schwarz** [comment]
Other possibility: Pretty uses `Obj.magic`, maybe breaking some assumptions of `flambda`. Though I think it is too early to suspect the compiler.

**Comment by michael-schwarz** [comment]
Seems like it is working as intended (as @sim642 explains here https://github.com/goblint/analyzer/issues/1290)

**Pull request closed without merging**
