### PR TITLE
build with dune

### PR DESCRIPTION
**Pull request by vogler**
Try `dune build src/cil.cmxa`; still need to generate `machdep.ml` (see `Makefile.in`).

Needed to build goblint with dune? See https://github.com/goblint/analyzer/pull/79.

### CODE REVIEW

**Comment by michael-schwarz** [comment]
Maybe we should do all this whitespace normalisation on master first instead of in here.
Like this, it's hard to see what the PR actually changes.

**Comment by vogler** [comment]
Was just changing it to another PR.

**Comment by vogler** [comment]
It's enough to build goblint now. I'll wait to check if macos-travis is happy with it and then merge.
We could also get rid of all the old configure/Makefile stuff and make the tests run with dune (see [diff/promote](https://dune.readthedocs.io/en/stable/tests.html#diffing-the-result)), but that's only relevant for cleanup/maintainability. Same applies to the warnings.

**Comment by michael-schwarz** [comment]
Sounds good!

On a related note, there's a bunch of warnings that we already have with ocamlbuild anyway, so those would also be candidates for cleanup.
Would be worth discussing whether we should remove all the stuff from "our" CIL that we don't use and did not change to support all the things we added in the past year. That would for example be all the CIL analyses and various other stuff such as the LLVM backend.
The downside of this is that our CIL diverges from the official one, the upside would be getting rid of a lot of old unused (and untested with our changes) code.

**Pull request merged**
