### PR TITLE
Remove unmaintained extensions

### PR DESCRIPTION
**Pull request by keremc**
This removes the extensions:

- simplemem
- canonicalize (makes C code C++ compliant, not useful for Goblint)
- llvm (not useful for Goblint, also probably broken)
- heapify ("move stack-allocated arrays to the heap", code instrumentation, not useful for Goblint)
- oneret
- logcalls (code instrumentation, not useful for Goblint)
- inliner (unfinished as far as I can tell)
- partial (unsound in some cases, see [thesis](https://github.com/goblint/cil/files/6343296/Comparison.of.Analyses.in.CIL.and.Goblint.pdf))
- blockinggraph (unfinished & not very useful, see [thesis](https://github.com/goblint/cil/files/6343296/Comparison.of.Analyses.in.CIL.and.Goblint.pdf))
- sfi (code instrumentation, not useful for Goblint)
- simplify
- cqualann
- logwrites (code instrumentation, not useful for Goblint)
- epicenter ("remove all functions except those within some number", code instrumentation, probably not useful for Goblint)
- ccl ("CCured Lite")

See #28

### CODE REVIEW

**Comment by michael-schwarz** [comment]
Can you please also modify the test suite such that the removed features are not tested, and it passes?

**Comment by keremc** [comment]
> Can you please also modify the test suite such that the removed features are not tested, and it passes?

OK. I deleted the tests related to "simplify". Some tests were failing because of the `--domakeCFG` option which was implemented in "partial", so I moved that part into a new extension called "makecfg".

**Comment by michael-schwarz** [comment]
@vogler @sim642 @jerhard Any objections to removing these?

**Comment by vogler** [comment]
No. Maybe cleanup the Readme and link this PR (or make a table/list that summarizes the diff to upstream (removed stuff, C99 features, fixed bugs, ?)).

**Comment by sim642** [comment]
I agree, updating the README and listing some bigger changes we've made could be useful.

**Comment by michael-schwarz** [comment]
Yes, good point! Can you also make the changes to the README in this PR @keremc?

Apart from the things in this PR, the substantial changes are:

- Some warnings are made optional
- Truncated integer constants have a string representation
- Compiles with OCaml >=4.06.0, use zarith instead of num
- C99 support #9 (entails changes to handling of VLA #5 #7)
- Syntactic Search as a new feature #21

**Comment by keremc** [comment]
OK, I updated the README to list the improvements made in `goblint-cil` and mentioned the opam package in the quick start. It is quite outdated at the moment, but I think @michael-schwarz plans to push an update.

**Pull request merged**
