### PR TITLE
Fix warnings reported by dune

### PR DESCRIPTION
**Pull request by vogler**
Fix warnings reported by dune.

### CODE REVIEW

**Comment by vogler** [comment]
> With this commit, we disabled running the unit tests on Travis. We should run them again.

Can't you just add [this](https://github.com/goblint/cil/blob/5ee6445f50f45fa1b7cc02ed6044a2b849122b03/opam.old#L12-L14):
~~~
run-test: [
  ["env" "VERBOSE=1" make "test"]
]
~~~
to `goblint-cil.opam.template` to run the tests as before?
Porting test-running to dune might offer some advantages, but I'm not sure if retrofitting it is worth the work.

**Comment by michael-schwarz** [comment]
Yes, sounds like a good idea in principle. The problem is that the test rely on `cilly` and we currently don't build the CIL binary or the `cilly` perl script from `dune`.
So we would have to run `make` before `make test` meaning everything gets built twice and we lose the advantage of `dune`.
So the approach I'm following right now, is to do the following:
1. Also generate the CIL binary in `dune build`
2. From `dune runtest`
    - Call `make` for the targets to create `cilly`
    - Call the regression test script as it is

So I'm doing the bare minimum to get it running without having to call `dune build` and `make` each time.
I have it working on my local machine with the code in the last commit except for 8 tests that still fail.

But maybe, I'm missing a really obvious solution here?

**Comment by vogler** [comment]
No, makes sense. The only shortcut would be to change `.travis.yml` to just run `make; make test`, but it's better if the CI installs the opam package and runs its tests.

**Comment by michael-schwarz** [comment]
It now works on Linux for OCaml `<= 4.07`.

**For OCaml `>= 4.08`**, the problem is that `Dataflow` is somehow not in the accessible modules for `dynlink`, so loading `goblint-cil.liveness` fails. It can be made accessible by referencing it from a module that is accessible anyway, but there should be a cleaner solution for this.

**For MacOS**, the problem is that I currently use `readlink -f` to get an absolute path from a relative path inside the `dune` file, and `-f` is not available on MacOS.

I'll work on these things next week.

**Pull request merged**
